GET http://localhost:3000

###

GET http://localhost:3000


###

GET http://localhost:3000

###

POST http://localhost:3000
content-type: application/json

{
    "name" : "Imre", 	
    "address" : "Baja", 	
    "phone" : "06204445566", 	
    "email" : "imi@gmail.com", 	
    "post" : "postás", 	
    "price" : 4500	
}

###

PATCH http://localhost:3000
content-type: application/json

{
    "id" : "101", 	
    "category" : "dairy", 	
    "productname" : "noodles ramen", 	
    "price" : "4200"
}

###

DELETE http://localhost:3000

###
